development:
  adapter: postgresql
  encoding: unicode
  database: augen_bookstore2
  pool: 10
  username: tuan
  password:
  host: postgres_postgresdb_1
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: augen_bookstore_test
  pool: 5
  username: tuan
  password:
  host: postgres_postgresdb_1
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: augen_bookstore
  pool: 5
  username: tuan
  password:
  host: postgres_postgresdb_1
  port: 5432